services:
  - type: web
    name: salary-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn modelwithdepapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

